# Generated by Django 5.0.6 on 2024-07-09 02:34

from django.db import migrations

def populate_status(apps, schemaeditor):
    entries = {
        "published": "A post that all users can see",
        "draft": "A post that only the author can see",
        "archived": "Older posts available to logged in users",
    }
    Status = apps.get_model("posts", "Status")
    for key, value in entries.items():
        status_obj = Status(name=key, description=value)
        status_obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_status)
    ]
